// website/src/routes/account/+page.svelte
<script lang="ts">
	import AccountForm from "./account-form.svelte";
	import type { PageData } from "./$types.js";
	import { Separator } from "$lib/components/ui/separator/index.js";

	export let data: PageData;
</script>

<div class="space-y-6">
	<div>
		<h3 class="text-lg font-medium">Account</h3>
		<p class="text-sm text-muted-foreground">
			Update your account settings. Set your preferred language and timezone.
		</p>
	</div>
	<Separator />
	<AccountForm data={data.form} />
</div>

// client/src/app/account/page.tsx
import { Separator } from "@/components/ui/separator"
import { AccountForm } from "@/app/account/account-form"

export default function SettingsAccountPage() {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium">Account</h3>
        <p className="text-sm text-muted-foreground">
          Update your account settings. Set your preferred language and
          timezone.
        </p>
      </div>
      <Separator />
      <AccountForm />
    </div>
  )
}
